#!/usr/bin/env python3
"""
Build per-browser extension bundles from a single source tree.

Firefox and Chrome disagree on two MV3 details:

  background   Firefox 115+ wants  {"scripts": [...]}
               Chrome         wants {"service_worker": "..."}
  id           Firefox needs browser_specific_settings.gecko.id for
               native messaging allowed_extensions; Chrome derives an id
               from the key/CRX instead.

Everything else is shared. Usage:

    python3 build.py                 # -> dist/firefox, dist/chrome
    python3 build.py --target chrome
    python3 build.py --version 1.2.0 # stamp a version (the release workflow
                                     # passes the tag, so the manifest version
                                     # and the git tag can never drift)
"""
import argparse, json, shutil, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "src"
ICONS = HERE / "icons"
DIST = HERE / "dist"

sys.path.insert(0, str(HERE))
import identity as IDENT  # noqa: E402  (path set immediately above)

IDENTITY = IDENT.load()
GECKO_ID = IDENTITY["geckoId"]
CHROME_KEY = IDENTITY.get("chromeKey") or ""
CHROME_ID = (IDENT.chrome_ids(IDENTITY) or [""])[0]

# optional_host_permissions landed in Firefox 128 (web-ext lint is the source
# of truth here - 116 was wrong and it caught it); the extension asks for the
# user's Audiobookshelf origin at runtime rather than holding <all_urls>.
FIREFOX_MIN = "128.0"

SHARED_FILES = [
    "background.js", "browser-polyfill.js", "lib.js", "content.js", "content.css",
    "popup.html", "popup.css", "popup.js", "options.html", "options.js",
]

ICON_FILES = ["icon-16.png", "icon-32.png", "icon-48.png", "icon-96.png", "icon-128.png"]


def manifest_for(target: str, version: str = None) -> dict:
    m = json.loads((SRC / "manifest.base.json").read_text())
    if version:
        m["version"] = version
    if target == "firefox":
        m["background"] = {"scripts": ["browser-polyfill.js", "config.js",
                                       "lib.js", "background.js"]}
        m["browser_specific_settings"] = {
            "gecko": {
                "id": GECKO_ID,
                "strict_min_version": FIREFOX_MIN,
                # The add-on sends nothing anywhere: the library is read from
                # the user's own server and the files go to their own device.
                # AMO will require this key; declaring "none" is both accurate
                # and the thing that keeps the listing out of a consent prompt.
                "data_collection_permissions": {"required": ["none"]},
            }
        }
    elif target == "chrome":
        # MV3 service workers are modules; importScripts is unavailable, so the
        # shim is pulled in with a static import from background.js instead.
        m["background"] = {"service_worker": "background.js", "type": "module"}
        m["minimum_chrome_version"] = "112"
        # A packed key pins the extension id, which the native host manifest
        # has to name. Empty until the Web Store issues one.
        if CHROME_KEY:
            m["key"] = CHROME_KEY
    else:
        raise SystemExit(f"unknown target {target!r}")
    return m


def build(target: str, version: str = None) -> Path:
    out = DIST / target
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    for name in SHARED_FILES:
        src = SRC / name
        if not src.exists():
            raise SystemExit(f"missing source file: {src}")
        shutil.copy2(src, out / name)

    (out / "icons").mkdir()
    for name in ICON_FILES:
        src = ICONS / name
        if not src.exists():
            raise SystemExit(f"missing icon: {src} (run extension/icons/make_icons.py)")
        shutil.copy2(src, out / "icons" / name)

    # Generated so the native host name lives in identity.json only - a
    # mismatch between here and native/install.py means the browser looks for
    # a host that was never registered, with no useful error.
    (out / "config.js").write_text(
        "/* generated by build.py - edit extension/identity.json instead */\n"
        "globalThis.ABSH_CONFIG = " + json.dumps({"hostName": IDENTITY["hostName"]}) + ";\n"
    )

    if target == "chrome":
        # background.js is loaded as an ES module here, so it must import the
        # shim itself rather than rely on a second "scripts" entry.
        bg = out / "background.js"
        bg.write_text('import "./browser-polyfill.js";\nimport "./config.js";\n'
                      'import "./lib.js";\n' + bg.read_text())

    (out / "manifest.json").write_text(
        json.dumps(manifest_for(target, version), indent=2) + "\n"
    )
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["firefox", "chrome", "all"], default="all")
    ap.add_argument("--version", help="override the manifest version (e.g. from a git tag)")
    a = ap.parse_args()
    targets = ["firefox", "chrome"] if a.target == "all" else [a.target]
    for t in targets:
        p = build(t, a.version)
        n = sum(1 for _ in p.rglob("*") if _.is_file())
        print(f"  built {t:8s} -> {p.relative_to(HERE)}  ({n} files)")


if __name__ == "__main__":
    main()
