/* folder.js against the helper's own answers.
 *
 * tests/fixtures/parity/*.json are generated by running absh (see
 * tools/parity_vectors.py); tests/python/test_parity_vectors.py fails if they
 * stop matching it. These assert the JavaScript port gives the same answers,
 * case by case, so a rule changed on one side fails the other side's tests.
 *
 * The filesystem here is memfs.js. tests/e2e/folder.spec.js runs the same
 * device, pull, push and remove cases against Chromium's real one. */
import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { MemDir } from "./memfs.js";
import "./parity-runner.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = (n) => JSON.parse(readFileSync(resolve(here, "../fixtures/parity", n), "utf8"));
const NAMING = fixture("naming.json");
const DEVICE = fixture("device.json");
const TAGS = fixture("tags.json");

let F;
const P = globalThis.PARITY;

beforeAll(async () => {
  await import("../../extension/src/folder.js");
  F = globalThis.ABSH_FOLDER;
});

const label = (x) => JSON.stringify(x);

describe("naming matches absh/naming.py", () => {
  it.each(NAMING.clean.map((c) => [label(c.in), c]))("clean(%s)", (_, c) => {
    expect(F.clean(c.in)).toBe(c.out);
  });
  it.each(NAMING.targetName.map((c) => [label(c.book), c]))("target name %s", (_, c) => {
    expect(F.targetName(c.book, c.template)).toBe(c.out);
  });
  it.each(NAMING.safeSubdir.map((c) => [label(c.in), c]))("safe subdir %s", (_, c) => {
    expect(F.safeSubdir(c.in)).toEqual(c.out);
  });
  it.each(NAMING.path.map((c) => [label(c.in), c]))("pathlib name/stem/suffix %s", (_, c) => {
    expect([F.pathName(c.in), F.stem(c.in), F.suffix(c.in)]).toEqual([c.name, c.stem, c.suffix]);
  });
  it.each(NAMING.outExt.map((c) => [label([c.in, c.rename]), c]))("out ext %s", (_, c) => {
    expect(F.outExt(c.in, c.rename)).toBe(c.out);
  });
  it.each(NAMING.sourceExt.map((c) => [label(c.in), c]))("source ext %s", (_, c) => {
    expect(F.sourceExt(c.in)).toBe(c.out);
  });
  it.each(NAMING.normKey.map((c) => [label([c.title, c.author]), c]))("norm key %s", (_, c) => {
    expect(F.normKey(c.title, c.author)).toEqual(c.out);
  });
  it.each(NAMING.normalizeItem.map((c) => [label(c.in.id), c]))("normalize item %s", (_, c) => {
    expect(F.normalizeItem(c.in)).toEqual(c.out);
  });
});

describe("tags match the built-in readers in absh/tags.py", () => {
  let got;
  beforeAll(async () => { got = await P.tags(F, TAGS); });
  it.each(TAGS.files.map((f) => [f.name, f]))("%s", (name, f) => {
    expect(got.files[name]).toEqual(f.out);
  });
  it.each(TAGS.books.map((b, i) => [label(b.files), i]))("book of %s", (_, i) => {
    expect(got.books[i]).toEqual(TAGS.books[i].out);
  });
});

describe("pull writes what sync.pull writes", () => {
  it.each(NAMING.pull.map((c) => [c.name, c]))("%s", async (_, c) => {
    expect(await P.pull(F, new MemDir(), c)).toEqual(c.expect);
  });
});

describe("push uploads what sync.push uploads", () => {
  it.each(NAMING.push.map((c) => [c.name, c]))("%s", async (_, c) => {
    expect(await P.push(F, new MemDir(), c)).toEqual(c.expect);
  });
});

describe("remove deletes what sync.remove deletes, and refuses what it refuses", () => {
  it.each(NAMING.remove.map((c) => [c.name, c]))("%s", async (_, c) => {
    expect(await P.remove(F, new MemDir(), c)).toEqual(c.expect);
  });
});

describe("scan and classification match device.scan and device.diff", () => {
  it.each(DEVICE.cases.map((c) => [c.name, c]))("%s", async (_, c) => {
    expect(await P.device(F, new MemDir(), c, DEVICE.server)).toEqual(c.expect);
  });
});

/* What the fixtures cannot say: behaviour that has no Python counterpart to
 * record, or that the browser does differently on purpose. */
describe("where the browser differs on purpose", () => {
  const zipOf = (name, data, crc) => {
    // One stored member, built by hand so the CRC can be wrong.
    const n = Buffer.from(name);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(n.length, 26);
    const cd = Buffer.alloc(46);
    cd.writeUInt32LE(0x02014b50, 0);
    cd.writeUInt32LE(crc, 16);
    cd.writeUInt32LE(data.length, 20);
    cd.writeUInt32LE(data.length, 24);
    cd.writeUInt16LE(n.length, 28);
    const end = Buffer.alloc(22);
    end.writeUInt32LE(0x06054b50, 0);
    end.writeUInt16LE(1, 8);
    end.writeUInt16LE(1, 10);
    end.writeUInt32LE(46 + n.length, 12);
    end.writeUInt32LE(30 + n.length + data.length, 16);
    return Buffer.concat([local, n, data, cd, n, end]);
  };
  const client = (body) => ({
    async download() { return { contentType: "application/zip", disposition: "", blob: new Blob([body]) }; },
  });
  const book = { id: "b", title: "Book", author: "Au" };

  it("a member whose CRC does not match fails, and leaves no partial file", async () => {
    const dev = new MemDir();
    const rep = await F.pull(client(zipOf("a.mp3", Buffer.from("hello"), 12345)), dev, [book],
                             { subdir: "AUDIOBOOKS" });
    expect(rep.errors).toEqual(["Book: download failed - Bad CRC-32 for file 'a.mp3'"]);
    const folder = await (await dev.getDirectoryHandle("AUDIOBOOKS")).getDirectoryHandle("Au - Book");
    // Not even an empty one: a part that exists is skipped next time, so an
    // empty file left here would keep the book a track short for good.
    expect([...folder.kids.keys()]).toEqual([]);
    // And so a second try fetches it again rather than skipping it.
    const again = await F.pull(client(zipOf("a.mp3", Buffer.from("hello"), 0x3610a686)), dev,
                               [book], { subdir: "AUDIOBOOKS" });
    expect([again.copied, again.skipped]).toEqual([1, 0]);
  });

  it("the same archive with the right CRC lands", async () => {
    const dev = new MemDir();
    const rep = await F.pull(client(zipOf("a.mp3", Buffer.from("hello"), 0x3610a686)), dev, [book],
                             { subdir: "AUDIOBOOKS" });
    expect(rep.errors).toEqual([]);
    expect(rep.copied).toBe(1);
  });

  it("refuses a backslash in a name to remove on every OS, not just Windows", async () => {
    const dev = new MemDir();
    await (await dev.getDirectoryHandle("AUDIOBOOKS", { create: true }))
      .getFileHandle("a.mp3", { create: true });
    const rep = await F.remove(dev, ["x\\..\\a.mp3"], { subdir: "AUDIOBOOKS" });
    expect(rep.errors).toEqual(["x\\..\\a.mp3: refusing a name that is not a single entry"]);
  });

  it("reads only the moov atom of a big file, not the whole file", async () => {
    const t = TAGS.files.find((f) => f.name === "moov at the end.m4a");
    const raw = Buffer.from(t.b64, "base64");
    let read = 0;
    const blob = new Blob([raw]);
    const spy = {
      size: blob.size,
      slice: (a, b) => {
        const s = blob.slice(a, b);
        return { arrayBuffer: async () => { read += s.size; return s.arrayBuffer(); } };
      },
    };
    expect((await F.readTags(spy, "x.m4a")).title).toBe(t.out.title);
    expect(read).toBeLessThan(raw.length / 2);
  });
});

describe("the commands, with a server and no browser", () => {
  /* run() is what the background calls. ping reads the stored folder from
   * IndexedDB, which node lacks; an empty store is all these need. */
  beforeAll(() => {
    const request = (result) => {
      const r = { result };
      queueMicrotask(() => r.onsuccess && r.onsuccess());
      return r;
    };
    globalThis.indexedDB = {
      open() {
        const tx = () => {
          const t = { objectStore: () => ({ get: () => ({ result: undefined }) }) };
          queueMicrotask(() => t.oncomplete && t.oncomplete());
          return t;
        };
        return request({ transaction: tx, close() {} });
      },
    };
  });

  it("says what is missing before trying the server", async () => {
    const p = await F.run("ping", { absUrl: "", apiKey: "" });
    expect(p).toMatchObject({ ok: true, backend: "folder", tags: "builtin", configured: false });
    expect(p.missing).toEqual(["absUrl (your Audiobookshelf URL)", "apiKey (Settings -> API Keys)"]);
  });

  it("reads libraries and folders the way abs_api.py does", async () => {
    const seen = [];
    const fakeFetch = async (url, init) => {
      seen.push([url, init.headers.Authorization]);
      const body = url.endsWith("/api/libraries")
        ? { libraries: [{ id: "podcasts", mediaType: "podcast" }, { id: "lib1", name: "B", mediaType: "book" }] }
        : { library: { folders: [{ id: "fol1", fullPath: "/books", extra: 1 }] } };
      return new Response(JSON.stringify(body));
    };
    const cfg = { absUrl: "http://abs.local:13378/", apiKey: "k" };
    expect(await F.run("libraries", cfg, undefined, fakeFetch))
      .toEqual({ libraries: [{ id: "lib1", name: "B", mediaType: "book" }] });
    expect(await F.run("folders", cfg, undefined, fakeFetch))
      .toEqual({ folders: [{ id: "fol1", fullPath: "/books" }] });
    expect(seen.map((s) => s[0])).toEqual([
      "http://abs.local:13378/api/libraries", "http://abs.local:13378/api/libraries",
      "http://abs.local:13378/api/libraries/lib1"]);
    expect(seen[0][1]).toBe("Bearer k");
  });

  it("explains a refused request in the helper's words", async () => {
    const fakeFetch = async () => new Response("nope", { status: 401 });
    await expect(F.run("libraries", { absUrl: "http://abs.local", apiKey: "k" }, undefined, fakeFetch))
      .rejects.toThrow("Audiobookshelf /api/libraries responded 401 - check the API key. nope");
  });
});
